services:
  - type: web
    name: imagine-tool
    runtime: docker
    plan: free
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
      - key: KLING_ACCESS_KEY
        sync: false
      - key: KLING_SECRET_KEY
        sync: false
      - key: FAL_KEY
        sync: false
      - key: HEDRA_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_IMAGE_MODEL
        value: gemini-2.0-flash-exp
      - key: KREA_API_KEY
        sync: false
